name: test

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Install stable toolchain
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          override: true

      - uses: Swatinem/rust-cache@v1
        with:
          working-directory: ./asc-bundler

      - name: Build asc-bundler
        working-directory: ./asc-bundler
        run: cargo build --verbose

      - name: Test asc-bundler
        working-directory: ./asc-bundler
        run: cargo test --verbose
